name: SafeFlyV2
author: Sean_M
version: "2.0.0"
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9]
description: Fly in survival without damaging players!
main: Sean_M\SafeFly\Main

commands:
    fly:
        description: "Activates or deactivates SafeFly."
        usage: "/fly"
        permission: safefly.fly
